import asyncio
import os
import sys

# Ensure python can find our modules
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from cost.auto_router import AutoRouter
from teams.team_factory import TeamFactory

async def run_dogfooding_campaign():
    print("🚀 Initializing itappens.ai Autonomous Marketing Campaign...")
    
    # Initialize the router and factory
    router = AutoRouter()
    factory = TeamFactory(auto_router=router)
    
    # Define the Marketing Brief for our own product
    marketing_brief = {
        "campaign_theme": "Why Weaponized GEO is replacing traditional SEO",
        "content_type": "LinkedIn Post Series",
        "primary_cta": "Get your free Weaponized GEO Audit at itappens.ai",
        "keywords": ["GEO", "AEO", "Perplexity", "ChatGPT search", "SEO is dead"],
        "deliverables": [
            "A short, punchy LinkedIn post calling out traditional SEO agencies",
            "A hook explaining what Citation Gravity is"
        ]
    }
    
    # Spawn the Marketing Crew targeting our own company profile (itappens_ai)
    team_id, crew, team_type, customer_id = factory.spawn_marketing_team(
        team_id="dogfood_marketing_1",
        marketing_brief=marketing_brief,
        customer_id="itappens_ai"
    )
    
    print(f"✅ Marketing Team Spawned. Agents: {[agent.role for agent in crew.agents]}")
    print("⏳ Executing Crew (this may take 1-3 minutes)...")
    
    # Run the team
    results = await factory.run_teams_in_parallel([
        (team_id, crew, team_type, customer_id)
    ])
    
    print("\n🎉 Mission Complete! Here is the output generated by your AI Marketing Team:")
    print("="*60)
    print(results[team_id]["output"])
    print("="*60)

if __name__ == "__main__":
    # Workaround for Windows asyncio EventLoopPolicy
    if sys.platform == 'win32':
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
        
    asyncio.run(run_dogfooding_campaign())
