var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/geo/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__74d5a847._.js")
R.c("server/chunks/ssr/node_modules_next_dist_65e60196._.js")
R.c("server/chunks/ssr/_36feffd5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a96fbe8a._.js")
R.c("server/chunks/ssr/node_modules_bc29e2c0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/app_e744e06a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_dd2abb83._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_geo_page_actions_4fa27c1b.js")
R.m(74783)
module.exports=R.m(74783).exports
