import { env } from "@/lib/env";
import { buildAbsoluteUrl, formatInr } from "@/lib/utils";
import nodemailer from "nodemailer";

function makeTransporter() {
    if (!process.env.GMAIL_USER || !process.env.GMAIL_APP_PASSWORD) return null;
    return nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: process.env.GMAIL_USER,
            pass: process.env.GMAIL_APP_PASSWORD,
        },
    });
}

async function sendEmail(payload: {
  to: string | string[];
  subject: string;
  html: string;
}) {
  if (env.RESEND_API_KEY) {
    await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${env.RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: env.MAIL_FROM,
        to: payload.to,
        subject: payload.subject,
        html: payload.html,
      }),
    });
    return;
  }

  const transporter = makeTransporter();
  if (transporter) {
    await transporter.sendMail({
      from: `"itappens.ai" <${process.env.GMAIL_USER}>`,
      to: payload.to,
      subject: payload.subject,
      html: payload.html,
    });
  }
}

type ReceiptEmailInput = {
  email: string;
  siteUrl: string;
  planLabel: string;
  amount: number;
};

export async function sendInternalLeadAlert(input: {
  email: string;
  siteUrl: string;
  planLabel: string;
  targetKeywords: string[];
}) {
  await sendEmail({
    to: "sadish.sugumaran@itappens.ai",
    subject: `New ${input.planLabel} audit lead for ${input.siteUrl}`,
    html: `
      <div style="font-family:Inter,system-ui,sans-serif;max-width:640px">
        <h2 style="margin-bottom:16px">New audit lead</h2>
        <p><strong>Website:</strong> ${input.siteUrl}</p>
        <p><strong>Email:</strong> ${input.email}</p>
        <p><strong>Plan:</strong> ${input.planLabel}</p>
        <p><strong>Keywords:</strong> ${input.targetKeywords.length ? input.targetKeywords.join(", ") : "Not provided"}</p>
      </div>
    `,
  });
}

export async function sendAuditReceiptEmail(input: ReceiptEmailInput) {
  await sendEmail({
    to: input.email,
    subject: `Audit confirmed for ${input.siteUrl}`,
    html: `
      <div style="font-family:Inter,system-ui,sans-serif;max-width:640px;color:#0f172a">
        <p style="font-size:12px;letter-spacing:.24em;text-transform:uppercase;color:#4f46e5">itappens.ai audit</p>
        <h1 style="font-size:28px;line-height:1.1;margin:0 0 18px">Your ${input.planLabel} is confirmed.</h1>
        <p style="color:#475569;line-height:1.7;margin:0 0 12px">
          We have queued the paid GEO + SEO deep audit for <strong>${input.siteUrl}</strong>.
          The system is now crawling the site, pulling SERP and competitor data, and generating the branded report.
        </p>
        <p style="color:#475569;line-height:1.7;margin:0 0 24px">
          Charge captured: <strong>${formatInr(input.amount)}</strong>.
        </p>
        <a href="${buildAbsoluteUrl("/audit")}" style="display:inline-block;background:#111827;color:#fff;padding:12px 22px;border-radius:999px;text-decoration:none;font-weight:600">
          Track audit status
        </a>
      </div>
    `,
  });
}

export async function sendAuditReadyEmail(input: {
  email: string;
  siteUrl: string;
  shareToken: string;
}) {
  const reportUrl = buildAbsoluteUrl(`/audit/report/${input.shareToken}`);

  await sendEmail({
    to: input.email,
    subject: `Your itappens.ai GEO audit is ready`,
    html: `
      <div style="font-family:Inter,system-ui,sans-serif;max-width:600px;background:#020617;color:#f8fafc;padding:48px 40px;border-radius:16px;border:1px solid #1e293b;margin:0 auto;">
        <div style="margin-bottom:32px;">
          <span style="font-size:26px;font-weight:800;letter-spacing:-0.03em;">
            it<span style="color:#e11d48;">appens</span>.ai
          </span>
        </div>
        <p style="font-size:11px;letter-spacing:.24em;text-transform:uppercase;color:#e11d48;margin:0 0 12px">Premium Audit Ready</p>
        <h1 style="font-size:32px;line-height:1.2;margin:0 0 16px;color:#ffffff;letter-spacing:-0.02em;">Your GEO + SEO Report is live.</h1>
        <p style="color:#94a3b8;line-height:1.7;margin:0 0 36px;font-size:16px;">
          The deep analysis for <strong>${input.siteUrl}</strong> is complete. We've compiled your technical crawl data, competitive gap analysis, and a 30-day execution roadmap into your interactive report.
        </p>
        <a href="${reportUrl}" style="display:inline-block;background:#e11d48;color:#ffffff;padding:16px 32px;border-radius:8px;text-decoration:none;font-weight:600;font-size:15px;letter-spacing:0.02em;box-shadow:0 4px 14px 0 rgba(225,29,72,0.39);">
          View Full Report &rarr;
        </a>
        <p style="margin-top:48px;padding-top:24px;border-top:1px solid #1e293b;font-size:12px;color:#475569;line-height:1.6;">
          Generated by the itappens.ai AEO Engine.<br>
          For questions, simply reply to this email or book your strategy call directly via the report page.
        </p>
      </div>
    `,
  });
}

export async function sendOTPEmail(input: { email: string; otp: string }) {
  await sendEmail({
    to: input.email,
    subject: `Your itappens.ai Verification Code: ${input.otp}`,
    html: `
      <div style="font-family:Inter,system-ui,sans-serif;max-width:640px;color:#0f172a">
        <div style="padding:24px 0 16px;">
          <span style="font-size:20px;font-weight:800;letter-spacing:-0.03em;">
            it<span style="color:#6366f1;">appens</span>.ai
          </span>
        </div>
        <p style="font-size:12px;letter-spacing:.24em;text-transform:uppercase;color:#4f46e5;margin-bottom:8px">Security Verification</p>
        <h1 style="font-size:28px;line-height:1.1;margin:0 0 18px">Your access code is <strong>${input.otp}</strong></h1>
        <p style="color:#475569;line-height:1.7;margin:0 0 24px">
          Enter this code to begin your free GEO audit. This code expires in 10 minutes.
        </p>
      </div>
    `,
  });
}

export async function sendContactAlert(input: {
  name: string;
  email: string;
  company: string;
  siteUrl: string;
  industry: string;
  message?: string;
}) {
  await sendEmail({
    to: "sadish.sugumaran@itappens.ai",
    subject: `New Contact Request from ${input.name} (${input.company})`,
    html: `
      <div style="font-family:Inter,system-ui,sans-serif;max-width:640px">
        <h2 style="margin-bottom:16px">New Contact Request</h2>
        <p><strong>Name:</strong> ${input.name}</p>
        <p><strong>Email:</strong> ${input.email}</p>
        <p><strong>Company:</strong> ${input.company}</p>
        <p><strong>Website:</strong> ${input.siteUrl}</p>
        <p><strong>Industry:</strong> ${input.industry}</p>
        <p><strong>Message:</strong></p>
        <blockquote style="border-left: 4px solid #e2e8f0; padding-left: 16px; color: #475569; white-space: pre-wrap;">${input.message || "No message provided."}</blockquote>
      </div>
    `,
  });
}

