'use client';
import { useState } from 'react';

interface PostPreviewProps {
  platform: 'linkedin' | 'instagram' | 'twitter';
  text: string;
  imageUrl?: string;
  scheduledAt?: string;
  status: 'pending' | 'draft' | 'approved';
  isPaid?: boolean;
  content_id?: string;
}

export default function PostPreview({ platform, text, imageUrl, scheduledAt, status, isPaid = true, content_id }: PostPreviewProps) {
  const [isApproving, setIsApproving] = useState(false);
  const [isApproved, setIsApproved] = useState(false);

  const handleApprove = async () => {
    if (!content_id) {
       // Mock for legacy entries without ID
       setIsApproving(true);
       setTimeout(() => { setIsApproved(true); setIsApproving(false); }, 1000);
       return;
    }
    setIsApproving(true);
    try {
      const res = await fetch('/api/social/post', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          content_id,
          platforms: [platform === 'linkedin' ? 'linkedin_personal' : platform],
          telegram_notify: true
        }),
      });
      const data = await res.json();
      if (data.results) {
        setIsApproved(true);
      }
    } catch (e) {
      console.error("Posting failed", e);
    } finally {
      setIsApproving(false);
    }
  };

  const getPlatformIcon = () => {
    switch (platform) {
      case 'linkedin': return '🔗';
      case 'instagram': return '📸';
      case 'twitter': return '🐦';
      default: return '📢';
    }
  };

  return (
    <div className="card-bento" style={{ padding: '24px', backgroundColor: 'var(--surface)', border: '1px solid var(--border)', display: 'flex', flexDirection: 'column', gap: '16px', opacity: isApproved ? 0.6 : 1, transition: 'opacity 0.3s' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <span style={{ fontSize: '18px' }}>{getPlatformIcon()}</span>
          <span style={{ fontWeight: 700, fontSize: '14px', textTransform: 'capitalize' }}>{platform} Draft</span>
          {isPaid && (
            <span style={{ 
              fontSize: '10px', 
              fontWeight: 800, 
              backgroundColor: 'var(--accent)', 
              color: '#fff', 
              padding: '2px 6px', 
              borderRadius: '4px',
              fontFamily: 'var(--font-mono)'
            }}>PRO</span>
          )}
        </div>
        <div style={{ fontSize: '12px', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
          {isApproved ? 'Approved ✅' : scheduledAt || 'Not scheduled'}
        </div>
      </div>

      <div style={{ padding: '16px', backgroundColor: 'var(--bg)', borderRadius: '12px', flex: 1 }}>
        <p style={{ fontSize: '14px', color: 'var(--text-dim)', margin: 0, whiteSpace: 'pre-wrap', lineHeight: 1.6 }}>
          {text.length > 150 ? text.slice(0, 150) + "..." : text}
        </p>
      </div>

      {imageUrl && (
        <div style={{ 
          height: '140px', 
          backgroundColor: '#000', 
          borderRadius: '12px', 
          overflow: 'hidden',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          color: '#fff',
          fontSize: '12px'
        }}>
          {/* IMAGE PREVIEW */}
          [Image Asset: Generated by itcontents]
        </div>
      )}

      <div style={{ display: 'flex', gap: '10px', marginTop: '8px' }}>
        <button 
          className="btn-primary" 
          onClick={handleApprove}
          style={{ 
            flex: 1, 
            padding: '10px', 
            fontSize: '13px',
            backgroundColor: isApproved ? 'var(--success, #22c55e)' : undefined,
            cursor: (isApproved || isApproving) ? 'not-allowed' : 'pointer'
          }}
          disabled={!isPaid || isApproving || isApproved}
        >
          {isApproving ? "Approving..." : isApproved ? "Scheduled in Buffer" : isPaid ? "Approve to Buffer" : "Upgrade to Post"}
        </button>
        {!isApproved && (
          <button className="btn-secondary" style={{ padding: '10px 16px', fontSize: '13px' }}>
            Edit
          </button>
        )}
      </div>
    </div>
  );
}
