var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/case-studies/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__5769701c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_65e60196._.js")
R.c("server/chunks/ssr/_4c5332a1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a96fbe8a._.js")
R.c("server/chunks/ssr/node_modules_bc29e2c0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/app_e744e06a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_dd2abb83._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_case-studies_page_actions_45bbcb4d.js")
R.m(54207)
module.exports=R.m(54207).exports
